# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=200)),
                ('fund_code', models.CharField(max_length=20)),
                ('fund_p_rate', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FundHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('netprice', models.DecimalField(decimal_places=4, max_digits=4)),
                ('note', models.CharField(max_length=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='RedemptionRateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('rate_value', models.DecimalField(decimal_places=4, default=0, max_digits=4)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Fund')),
            ],
        ),
    ]
