# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_p_rate',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='purchase rate'),
        ),
        migrations.AlterField(
            model_name='fundhistory',
            name='date',
            field=models.DateField(verbose_name='history date'),
        ),
        migrations.AlterField(
            model_name='fundhistory',
            name='netprice',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='net price'),
        ),
        migrations.AlterField(
            model_name='fundhistory',
            name='note',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='redemptionratetable',
            name='days',
            field=models.IntegerField(default=0, verbose_name='in thers days'),
        ),
    ]
