# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_auto_20170629_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruchaseTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ack_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='net amount')),
                ('netprice', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('holdon_shares', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='hold on shares')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Fund')),
            ],
        ),
    ]
