# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_pruchasetrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruchasetrade',
            name='ack_date',
            field=models.DateField(default=datetime.date(2017, 7, 3), verbose_name='confirm date'),
        ),
    ]
