# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_pruchasetrade_ack_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruchasetrade',
            name='ack_date',
        ),
    ]
