# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_redemptiontrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruchasetrade',
            name='redemption_shares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='redemption shares'),
        ),
    ]
